apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: api-gateway