apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
