apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-ingress
  namespace: m
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx-m
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: health-service
                port:
                  number: 80
          - path: /otusapp/[^/]+/health
            pathType: ImplementationSpecific
            backend:
              service:
                name: health-service
                port:
                  number: 80